### ISSUE TITLE
register route not working

### ISSUE THREAD

**Issue by danonel** [asbaba-corp/auth#35]
/register returning internal server error

response: {"message":"Internal Server Error"}
method: POST
url: https://qkcy9ocpg8.execute-api.us-east-1.amazonaws.com/register
payload: {
    "email": "asbaba@junior.com",
    "password": "123456"
}

log from cloudwatch:

https://us-east-1.console.aws.amazon.com/cloudwatch/home?region=us-east-1#logsV2:log-groups/log-group/$252Faws$252Flambda$252Fcataprato-auth-lambda/log-events/2023$252F08$252F17$252F$255B$2524LATEST$255Da4ae5c9abbe5462e9059abf74ffa0c2e

2023-08-17T11:14:46.019-03:00 | INIT_START Runtime Version: python:3.10.v10 Runtime Version ARN: arn:aws:lambda:us-east-1::runtime:88cda47888625b0f7511aee0c30343c278276a1534d5f8362dc3d68a5c88d56d
  | 2023-08-17T11:14:46.163-03:00 | START RequestId: e133f887-bf55-404a-bcca-37140917b586 Version: $LATEST
  | 2023-08-17T11:14:46.166-03:00 | [ERROR] Runtime.ImportModuleError: Unable to import module 'main': No module named 'main' Traceback (most recent call last):
  | 2023-08-17T11:14:46.167-03:00 | END RequestId: e133f887-bf55-404a-bcca-37140917b586
  | 2023-08-17T11:14:46.167-03:00 | REPORT RequestId: e133f887-bf55-404a-bcca-37140917b586 Duration: 4.33 ms Billed Duration: 5 ms Memory Size: 128 MB Max Memory Used: 36 MB Init Duration: 142.25 ms

**Comment by juniozguedes** [comment]
Fixing right now, I know what is the problem.
It's regarding wrong architecture deployment, I already aligned with Felipe and we'll be fixing.

Right now I will apply a workaround manually so this route will work for you, give me 5 mins

**Comment by juniozguedes** [comment]
It works now, please try!
![image](https://github.com/asbaba-corp/auth/assets/25936222/b9858e43-05db-4865-89c8-35b3d0e29bda)

**Comment by juniozguedes** [comment]
Reopening issue until it works with Insomnia/Postman

**Comment by juniozguedes** [comment]
Hey there rocker! It's working via Insomnia, can u check and close the issue pls?
![image](https://github.com/asbaba-corp/auth/assets/25936222/e83d345d-567e-4063-9afe-bf8a912ce4b4)

**Comment by juniozguedes** [comment]
Fixed
